const types = Object.freeze({
    INCREMENT_COUNTER: "INCREMENT_COUNTER",
    DECREMENT_COUNTER: "DECREMENT_COUNTER",
    RESET_COUNTER: "RESET_COUNTER",
    SET_TEXT: "SET_TEXT",
    RESET_INPUT: "RESET_INPUT",
    SET_TASKS: "SET_TASKS",
    LOADING: "LOADING",
    TOGGLE_ADD_MODAL: "TOGGLE_ADD_MODAL",
    ADD_TASK: "ADD_TASK",
    DELETE_SINGLE_TASK: "DELETE_SINGLE_TASK",
    EDIT_TASK: "EDIT_TASK",
    TOGGLE_CHECKED_TASK: "TOGGLE_CHECKED_TASK",
    REMOVE_SELECTED_TASKS: "REMOVE_SELECTED_TASKS",
    TOGGLE_SELECT_TASKS: "TOGGLE_SELECT_TASKS",
    TOGGLE_CONFIRM_MODAL: "TOGGLE_CONFIRM_MODAL",
    TOGGLE_EDIT_MODAL: "TOGGLE_EDIT_MODAL",
    SET_SUCCESS: "SET_SUCCESS",
    SET_ERROR_MESSAGE: "SET_ERROR_MESSAGE",
    SET_FORM_DATA_EMPTY: "SET_FORM_DATA_EMPTY",
    SET_CHANGES: "SET_CHANGES",
    TOGGLE_EDIT_TASK: "TOGGLE_EDIT_TASK",
    SET_SINGLE_TASK: "SET_SINGLE_TASK"


});

export default types;
